### ISSUE TITLE
Error: unknown option '-d'

### ISSUE THREAD

**Issue by daveypea** [THoenig/11ty-bs5-starter#1]
Hey, just looking at this repository. I wonder if you could help with an error i'm getting.

daveyp@DAVEP 11ty-bs5-starter % npm run build         

> 11ty-bootstrap5@1.0.0 build
> cross-env NODE_ENV=production npm-run-all clean --parallel build:* --serial purgecss

> 11ty-bootstrap5@1.0.0 clean
> rimraf public/ .cache/

> 11ty-bootstrap5@1.0.0 build:eleventy
> eleventy

> 11ty-bootstrap5@1.0.0 build:parcel
> parcel build parcel.js -d ./public/_assets -o main --public-url '/_assets' --no-source-maps

error: unknown option '-d'
npm ERR! code 1
npm ERR! path /Users/daveyp/Sites/11ty-bs5-starter
npm ERR! command failed
npm ERR! command sh -c parcel build parcel.js -d ./public/_assets -o main --public-url '/_assets' --no-source-maps

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daveyp/.npm/_logs/2021-03-19T22_41_39_607Z-debug.log
ERROR: "build:parcel" exited with 1.
npm ERR! code 1
npm ERR! path /Users/daveyp/Sites/11ty-bs5-starter
npm ERR! command failed
npm ERR! command sh -c cross-env NODE_ENV=production npm-run-all clean --parallel build:* --serial purgecss

**Comment by THoenig** [comment]
Hi Dave!

That's strange. I tested it, it runs on my machine ;)

Would you mind sharing your installed version of parcel (```npx parcel --version```) as well as the npm debug log ( ```/Users/daveyp/.npm/_logs/2021-03-19T22_41_39_607Z-debug.log```)?

**Comment by daveypea** [comment]
Parcel version: `2.0.0-beta.2`
Note: I've tried a few things, reinstalling everything. A simple `parcel serve ./src/index.html` command works without error.

Anyway here's the logfile:
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
1 info using npm@7.6.3
2 info using node@v14.16.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/daveyp/Sites/11ty-bs5-starter/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/daveyp/.npmrc Completed in 2ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 3ms
13 timing config:load:global Completed in 3ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 15ms
19 verbose npm-session 252dcfec8f9b24d1
20 timing npm:load Completed in 26ms
21 timing command:run Completed in 47ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose pkgid 11ty-bootstrap5@1.0.0
24 verbose cwd /Users/daveyp/Sites/11ty-bs5-starter
25 verbose Darwin 19.6.0
26 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
27 verbose node v14.16.0
28 verbose npm  v7.6.3
29 error code 127
30 error path /Users/daveyp/Sites/11ty-bs5-starter
31 error command failed
32 error command sh -c cross-env NODE_ENV=development run-p watch:*
33 verbose exit 127

**Comment by THoenig** [comment]
Thanks, I figured out the problem.

You have Parcel 2 installed, which doesn't know the option ```-d```. This is kind of weird, because this project explicitly wants version 1.12.4 (line 36 in ```package.json```). But perhaps you have installed version 2 globally...

I think the easiest way to get around this is to change the option in line 10 of ```package.json``` from ```-d``` to ```--dist-dir```.

**Comment by daveypea** [comment]
Thank you!

**Comment by daveypea** [comment]
Ha tragic. I'm getting an error now on the `-o`. I've tried to change this to `--output` but it doesn't recognise it. Any ideas?


`error: unknown option '-o'
npm ERR! code 1
npm ERR! path /Users/daveyp/Sites/11ty-bs5-starter
npm ERR! command failed
npm ERR! command sh -c parcel watch parcel.js --dist-dir ./public/_assets -o main --public-url '/_assets'`

**Comment by THoenig** [comment]
Sorry, I should have given you the link to the [Parcel 2 migration page](https://v2.parceljs.org/getting-started/migration/#--out-file). You should find any information you need there.

Please note:
Parcel 2 is out of scope of this project and I don't intend to support it (at least as long as it is in beta). Maybe you want to try ```npm uninstall parcel && npm install --save-dev parcel@1.12.4```. This explicitly installs the correct version which is guaranteed to work with the default run targets.
